= Given: `CommandSpec`

The static methods in `CliAssured` class are the main entry points into the CLI Assured API.
They all return a `CommandSpec` instance.

== Command and its arguments

The most common way to specify the executable and its arguments is to use `CommandSpec.command(String executable, String... arguments)`.

The `executable` can be any of the following:

** An absolute path
** If `CommandSpec.cd(path)` was specified, then `executable` can be a path relative to that directory
** A directory relative to the working directory of the current JVM
** Plain command name of the command can be found in `PATH` environment variable.

[source,java]
----
include::example$j21/CommandSpecCommandTest.java[tag=imports]

include::example$j21/CommandSpecCommandTest.java[tag=command,indent=0]
----

=== Add arguments separately

If you need to add the arguments in several iterations, you can use the following pattern:

[source,java]
----
include::example$j21/CommandSpecCommandTest.java[tag=imports]

include::example$j21/CommandSpecCommandTest.java[tag=executableArgs,indent=0]
----

== Special `CommandSpec` factories

CLI Assured offers special `CommandSpec` factories for the `java` executable of the current JVM process and for Maven.

=== `CliAssured.java()`

`CliAssured.java()` creates a `CommandSpec` with the `java` executable of the current JVM pre-configured.
The executable is resolved from the `java.home` system property.

[source,java]
----
include::example$j21/CommandSpecJavaTest.java[tag=imports]

include::example$j21/CommandSpecJavaTest.java[tag=javaVersion,indent=0]
----

=== Maven

== Environment variables

Use `CommandSpec.env(String name, String value, String... more)` to set one or more environment variables for the command.
Note that the number of additional arguments must be even. Each name must have a corresponding value.
Here is a basic example:

[source,java]
----
include::example$j21/EnvTest.java[tag=imports]

include::example$j21/EnvTest.java[tag=multiple,indent=0]
----

[TIP]
====
There is also `CommandSpec.env(Map<String, String> variables)` accepting a map from variable names to their respective values.
====


== Working directory

Use `CommandSpec.cd(Path workDirectory)` to set the working directory of the spawned process.
The command's executable and any relative file paths will be resolved against this directory.
If `cd()` is not called, the working directory defaults to the current JVM's working directory.

[source,java]
----
include::example$j21/CdTest.java[tag=imports]

include::example$j21/CdTest.java[tag=snippet,indent=0]
----

[TIP]
====
`given()` and `when()` methods we used in the above snippet are just syntactic sugar.
Using `CliAssured.command("cat", "hello.txt").cd(myWorkDir)` would have exactly the same effect.
====

== Redirect `stderr` to `stdout`

Use `CommandSpec.stderrToStdout()` to redirect the standard error output of the spawned process to its standard output.
This is useful when you want to assert on `stderr` content using the `stdout()` assertions, or when the command mixes output
across both streams and you want to capture everything in one place.

Note that once `stderrToStdout()` is enabled, calling `stderr()` on the expectations will throw an `IllegalStateException`.

[source,java]
----
include::example$j21/StderrToStdoutTest.java[tag=imports]

include::example$j21/StderrToStdoutTest.java[tag=snippet,indent=0]
----

== Send a file to `stdin`

== Write to `stdin`

Use `CommandSpec.stdin(Consumer<OutputStream>)` to write arbitrary data to the process' standard input.
The consumer receives an `OutputStream` connected to the process' `stdin` and is called on a dedicated thread.
CLI Assured closes the stream automatically after the consumer returns.

Exceptions thrown from the consumer are caught and reported when `CommandResult.assertSuccess()` is called.
You may call only one of the `stdin(...)` methods per `CommandSpec` chain.

[source,java]
----
include::example$j21/WriteToStdinTest.java[tag=imports]

include::example$j21/WriteToStdinTest.java[tag=snippet,indent=0]
----

== Auto-close behavior

== Thread pool
