= Run a command and get the output

Although CLI Assured was primarily designed for testing CLI applications,
it also offers shortcuts to run a command and get the output as a stream of lines or as a byte array without too much typing.

[[lines]]
== Redirect `stderr` to `stdout` and get all output lines

`CommandSpec.lines()` is a convenience shorthand that executes the command, redirects `stderr` to `stdout`, captures all output,
asserts success, and returns a stream of lines captured on `stdout`.

[source,java]
----
include::example$j21/GetStdOutLinesTest.java[tag=imports]

include::example$j21/GetStdOutLinesTest.java[tag=snippet,indent=0]
----


[[bytes]]
== Redirect `stderr` to `stdout` and get all output as a byte array

`CommandSpec.bytes()` is a convenience shorthand that executes the command, redirects `stderr` to `stdout`, captures all output,
asserts success, and returns the raw bytes captured on `stdout`.

[source,java]
----
include::example$j21/CommandSpecBytesTest.java[tag=imports]

include::example$j21/CommandSpecBytesTest.java[tag=snippet,indent=0]
----

[NOTE]
====
The above snippets are a shot version of the following:

[source,java]
----
include::example$j21/GetStdOutLinesTest.java[tag=full,indent=0]
----
====
