#
# SPDX-FileCopyrightText: Copyright (c) 2025 CLI Assured contributors as indicated by the @author tags
# SPDX-License-Identifier: Apache-2.0
#

site:
  title: CLI Assured
  start_page: cli-assured:ROOT:index.adoc
content:
  sources:
  - url: ./../
    branches: HEAD
    start_path: docs

ui:
  supplemental_files: ./supplemental-ui
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

antora:
  extensions:
  - require: '@antora/lunr-extension'

output:
  dir: ./target/site
