name: verify

on:
  pull_request

permissions:
  discussions: read
  issues: read
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      - name: mvn install -DskipTests -e -B -ntp
        shell: bash
        run: ./mvnw install -DskipTests -e -B -ntp

      - name: Upload ~/.m2/repository
        uses: actions/upload-artifact@v7
        with:
          name: local-maven-repo-${{ github.sha }}
          path: ~/.m2/repository

  test:
    name: Test
    needs: install

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
        jdk: [ "8", "11", "17", "21", "25" ]
        exclude:
        - os: macos-latest
          jdk: "8"
    runs-on: ${{ matrix.os }}

    steps:

      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'

      - id: maven-m2
        shell: bash
        run: |
          echo "repo=$(./mvnw help:evaluate -Dexpression=settings.localRepository -q -DforceStdout)" >> $GITHUB_OUTPUT

      - shell: bash
        run: |
          echo "steps.maven-m2.outputs.repo=${{ steps.maven-m2.outputs.repo }}"

      - name: Download ~/.m2/repository
        uses: actions/download-artifact@v8
        with:
          name: local-maven-repo-${{ github.sha }}
          path: ${{ steps.maven-m2.outputs.repo }}

      - run: ./mvnw test -e -B -ntp -pl ':cli-assured-tests'
        if: ${{ matrix.jdk < 21 }}

      - run: ./mvnw test -e -B -ntp -pl ':cli-assured-tests,:cli-assured-tests-java21'
        if: ${{ matrix.jdk >= 21 }}

      - run: ./mvnw test -e -B -ntp -pl ':cli-assured-docs'
        if: ${{ matrix.jdk == 25 && matrix.os == 'ubuntu-latest' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail on uncommitted changes
        shell: bash
        run: |
          [[ -z $(git status --porcelain) ]] || {
            echo 'There are uncommitted changes'
            git status
            git diff
            exit 1
          }
